const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

const config = {
  mode: 'development',
  entry: ['@babel/polyfill','./src/index.js'],
  devtool: 'inline-source-map',
  resolve: {
    alias: {
      assets: path.resolve(__dirname, './src/assets')
    }
  },
  devServer: {
    contentBase: path.join(__dirname, 'public'),
    compress: true
  },
  output: {
    path: path.resolve(__dirname, 'public'),
    filename: '[name].[contenthash].js'
  },
  module: {
    rules: [
      {
       test: /\.css$/i,
       use: [
         MiniCssExtractPlugin.loader,
         {
           loader: 'css-loader',
           options: {
              modules: true,
              sourceMap: true,
              importLoaders: 2,
              localIdentName: '[name]__[local]___[hash:base64:5]'
           }
         },
         'postcss-loader'
       ]
      },
      {
        test: /\.js$/i,
        use: 'babel-loader',
        exclude: /node_modules/
      },
      {
        test: /\.scss$/i,
        use: [
          MiniCssExtractPlugin.loader,
          'css-loader',
          'sass-loader',
        ]
      },
      {
        test: /\.(png|jpe?g|webp|gif)$/i,
        use: [ 
          {
            loader: 'responsive-loader',
            options: {
              adapter: require('responsive-loader/sharp'),
              sizes: [300, 600, 1200, 2000],
              placeholder: true,
              placeholderSize: 50
            }
          },
          {
            loader: 'url-loader',
            options: {
              esModule: false,
              // limit: 10000,
              // emitFile: true,
              // useRelativePath: true,
            }
          }
        ]
      },
      {
        test: /\.svg$/,
        use:'file-loader'
      },
      { test: /\.html$/i,
        use: [
          {
            loader: 'html-loader',
            options: {
              interpolate: true
            }
          }
        ]
      },
    ]
  },
  plugins:[
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack,
      hash: true,
      template: './src/index.html',
      filename: 'index.html',
      entryPoint: path.resolve(__dirname, 'public') + '/index.html',
    }),
   new MiniCssExtractPlugin()
  ],
  optimization: {
    runtimeChunk: 'single',
    splitChunks:{
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors',
          chunks: 'all'
        }
      }
    }
  }
};


module.exports = config;